draw_config:
  n_columns: 1
  draw_key_sides: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 180.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  svg_extra_style: |
    /* For default sytles, see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L85 */

    svg.keymap {
      font-family: Sometype Mono, Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 18px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
      fill: #777;
    }
    
    /* default key styling */
    rect.key {
      fill: #272727;
    }
    rect.key, rect.combo {
      stroke: #111;
      stroke-width: 1;
    }
    /* color accent for combo boxes */
    rect.combo, rect.combo-separate {
      fill: #0f577e;
    }
    
    /* styling for combo dendrons */
    path.combo {
      stroke-width: 6;
      stroke-linecap: round;
      stroke: #554a34;
      fill: none;
    }
    .layer-M-BTNS-🖰 .combopos-0 {
      translate: 0px 45px;
    }
    
    /* default key side styling, only used is draw_key_sides is set */
    rect.side {
      filter: brightness(80%);
    }

    text {
      text-anchor: middle;
      dominant-baseline: hanging;
    }
    
    /* styling for layer labels */
    text.label {
      font-size: 32px;
      font-weight: bold;
      text-anchor: start;
      stroke: black;
      stroke-width: 6;
      paint-order: stroke;
    }
    text.layer-activator {
      font-size: 24px;
      font-weight: bold;
      text-decoration: none;
      stroke: #777;
    }
    text.layer-activator:not(.combo) {
      translate: 0px -9px;
    }
    
    /* fainter symbol for transparent keys */
    text.trans {
      fill: #050505;
    }
    
    /* styling for key non-tap label text */
    text.hold, text.shifted, text.left, text.right {
      font-size: 18px;
      font-weight: bold;
      fill: #b8ca2f;
    }
    
    text.combo {
      font-size: 32px;
      dominant-baseline: middle;
      font-weight: normal;
    }
    
    text.hold {
      text-anchor: middle;
      dominant-baseline: auto;
    }
  
    text.shifted {
      text-anchor: middle;
      dominant-baseline: hanging;
    }

    /* Color accent for held keys */
    rect.held, rect.combo.held, rect.layer-activator {
      fill: #622fca;
    }
    
    text.font24 {
      font-size: 24px;
    }
    text.font30 {
      font-size: 30px;
    }
    text.space.tap {
      font-size: 32px;
      translate: 0px -10px;
    }
    text.space.shifted {
      font-size: 24px;
      translate: 0px 4px;
    }
    text.tab {
      translate: 0px 2px;
    }
    text.esc {
      font-size: 32px;
      font-weight: bold;
      dominant-baseline: middle;
      fill: #050505;
      stroke: #050505;
      translate: 0px 4px;
    }
    rect.esc {
      fill: #ca5b2f;
    }
    text.ctrl {
      font-size: 30px;
      translate: 0px -5px;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Toggle */
    .toggle.shifted {
      translate: -10px 12px;
    }

    .toggle.hold {
      translate: 13px -23px;
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }

  shrink_wide_legends: 5
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  mark_alternate_layer_activators: false
  sticky_label: stky
  toggle_label: togl
  trans_legend:
    tap: ▽
    type: trans

  raw_binding_map:
    # Layers
    "&to ALPHAS":
      tap: 𝜶
      type: layer-activator
    "&mo DIGITS":
      tap: ℤ
      type: layer-activator
    "&sl FUNCTS":
      tap: 𝒇
      type: layer-activator
    "&mo SYMBLS":
      tap: ±
      type: layer-activator
    "&mo M_BTNS":
      tap: 🖰
      type: layer-activator
    "&mo SCROLL":
      tap: 🡙
      type: layer-activator
    "&mo LOWDPI":
      tap: 🕀
      type: layer-activator

    # Mouse
    "&mkp MB1":
      tap: '⭷🖰L'
    "&mkp MB2":
      tap: 'R🖰⭶'
    "&mkp MB3":
      tap: 'M🖱⭱'
    "&mkp MB4":
      tap: '🡨B'
    "&mkp MB5":
      tap: 'F🡪'

    # Modifiers
    "&td_SHFTCAPS":
      tap: ⇧
      shifted: ⇪1-⇪🔏
      type: font24
    "&macro_hex_pfx":
      tap: '0x'
    "&uc 0x2014 0":
      tap: —
    "&morph_JUSTDOT":
      tap: '.'
      shifted: ''
    "&morph_JUSTCOMMA":
      tap: ','
      shifted: ''
    "&morph_SPACEUNDER":
      tap: ␣
      shifted: _
      type: space

    # Empty
    "&none":
      tap: ""
      type: none

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: "$"
    DLLR: "$"
    PERCENT: "%"
    PRCNT: "%"
    CARET: "^"
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: "("
    LPAR: "("
    RIGHT_PARENTHESIS: ")"
    RPAR: ")"
    KP_PLUS: "+"
    KP_MINUS: "-"
    KP_MULTIPLY: "*"
    KP_DIVIDE: "/"
    EQUAL: "="
    PLUS: "+"
    MINUS: "-"
    UNDERSCORE: "_"
    UNDER: "_"
    SLASH: "/"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: '\'
    BSLH: '\'
    NON_US_BACKSLASH: '\'
    NON_US_BSLH: '\'
    PIPE: "|"
    PIPE2: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE:
      tap: "'"
      shifted: '"'
    APOS:
      tap: "'"
      shifted: '"'
    LS(APOS): '"'
    DOUBLE_QUOTES: '"'
    DQT: '"'
    LESS_THAN: "<"
    LT: "<"
    PERIOD: '.'
    DOT: "."
    COMMA: ","
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT:  "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    LS(GRAVE): "~"
    TILDE: "~"
    TILDE2: "~"
    NON_US_HASH: "#"
    NUHS: "#"

    # Numbers
    N1: "1"
    N2: "2"
    N3: "3"
    N4: "4"
    N5: "5"
    N6: "6"
    N7: "7"
    N8: "8"
    N9: "9"
    N0: "0"

    # Modifiers
    LCTRL:
      tap: ⎈
      type: ctrl
    RCTRL:
      tap: ⎈
      type: ctrl

    LALT: ⎇
    RALT: ⎇

    LSHFT:
      tap: ⇧
      type: font30
    RSHFT:
      tap: ⇧
      type: font30

    CAPS: ⇪

    LGUI: 🐧
    RGUI: 🐧

    LC(C): 🗐
    LC(X): ✀
    LC(V): 📋︎
    LC(S): 🖫

    # Arrows
    UP: ▲
    UP_ARROW: ▲
    DOWN: ▼
    DOWN_ARROW: ▼
    LEFT_ARROW: ◀
    LEFT: ◀
    RIGHT: ▶
    RIGHT_ARROW: ▶
    HOME: '↤H'
    END: 'E↦'
    PG_UP: '↥U'
    PAGE_UP: '↥U'
    PG_DN: '↧D'
    PAGE_DOWN: '↧D'
    INSERT: ⎀

    # Whitespace
    ENTER:
      tap: ↵
      type: font24
    RET:
      tap: ↵
      type: font24
    ESC:
      tap: ⎋
      type: esc
    ESCAPE:
      tap: ⎋
      type: esc
    TAB:
      tap: ↹
      type: tab
    LS(TAB):
      tap: ↹
      type: tab
    SPACE:
      tap: ␣
      type: space
    BACKSPACE:
      tap: 🠴
      type: font24
    BSPC:
      tap: 🠴
      type: font24
    DELETE:
      tap: 🠶
      type: font24
    DEL:
      tap: 🠶
      type: font24

    # Sound
    K_VOL_UP: 🕪
    K_VOL_DN: 🕩
    C_MUTE: 🕨
    C_VOL_UP: 🕪
    C_VOL_DN: 🕩
    C_VOLUME_UP: 🕪
    C_VOLUME_DOWN: 🕩

    # Media
    C_NEXT: ⏭
    C_PREV: ⏮
    C_PP: ⏯
    C_PLAY_PAUSE: ⏯

    combo_semicolon:
      key:
        shifted: ":"
        hold: ";"

    combo_tab:
      align: "mid"

    combo_emdash:
      align: "top"

    combo_functions_layer:
      align: "top"

    combo_middle_click:
      align: "mid"