#Config option descriptions taken from https://github.com/trentrand/zmk-pmw3360-driver/blob/main/Kconfig

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610=y

CONFIG_PMW3610_SMART_ALGORITHM=y #Enable the integration of the smart algorithm as the datasheet implementation.
                                 #The algorithm is used to extend the tracking acrocss a wider range of surfaces
                                 #such as graniles and tiles

CONFIG_PMW3610_CPI=3200 #range 200 to 3200, with 200 step; default is 800
CONFIG_PMW3610_CPI_DIVIDOR=1 #range 1 to 100, with 1 being faster, 100 being slower

CONFIG_PMW3610_SNIPE_CPI=1024 #same as above, but for snipe mode
CONFIG_PMW3610_SNIPE_CPI_DIVIDOR=1

#CONFIG_PMW3610_BALL_ACTION_TICK ???????? possibly not a valid config option
CONFIG_PMW3610_SCROLL_TICK=32 #default is 20

CONFIG_PMW3610_POLLING_RATE_250=y #boolean assigned options are:
                                  #PMW3610_POLLING_RATE_250 for 250hz
                                  #PMW3610_POLLING_RATE_125 for 125hz
                                  #PMW3610_POLLING_RATE_125_SW for 125hz with software implementation

CONFIG_PMW3610_FORCE_AWAKE=y #This setting forces the sensor to always be in the RUN state

###Time in milliseconds after which sensor goes from this mode to the next mode below, e.g. from RUN -> REST1 -> REST2 -> REST3
#CONFIG_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264 #range 13 to 3264, default is 128
#CONFIG_PMW3610_REST1_DOWNSHIFT_TIME_MS=9600 #default is 9600
#CONFIG_PMW3610_REST2_DOWNSHIFT_TIME_MS= #default is 0, no optimal value provided by the datasheet

#CONFIG_PMW3610_REST1_SAMPLE_TIME_MS=5 #range 10 to 2550, default is 40
#CONFIG_PMW3610_REST2_SAMPLE_TIME_MS= #range 10 to 2550, default is 0
#CONFIG_PMW3610_REST3_SAMPLE_TIME_MS= #range 10 to 2550, default is 0

CONFIG_PMW3610_ORIENTATION_180=y #boolean assigned options are:
                                 #PMW3610_ORIENTATION_0 for no rotation
                                 #PMW3610_ORIENTATION_90 for 90 deg clockwise
                                 #PMW3610_ORIENTATION_180 for 180 deg clockwise
                                 #PMW3610_ORIENTATION_270 for 270 deg clockwise

#config PMW3610_INVERT_X=n
#config PMW3610_INVERT_Y=n

CONFIG_PMW3610_INVERT_SCROLL_X=y
CONFIG_PMW3610_INVERT_SCROLL_Y=n

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_PMW3610_AUTOMOUSE_TIMEOUT_MS=1 #default is 400
CONFIG_PMW3610_MOVEMENT_THRESHOLD=0
