on:
  push:
    # be aware of limited YAML anchor syntax support in GH Actions. See https://frenck.dev/github-actions-yaml-anchors-aliases-merge-keys/
    paths-ignore: &PATHS_IGNORE
      - 'workflows/keymap_drawer.yml'
      - 'config/keyball44.json'
      - 'keymap-drawer/*'
      - '.gitignore'
      - 'keymap_drawer.config.yaml'
      - 'README.md'
  pull_request:
    paths-ignore: *PATHS_IGNORE
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
